version: 2

# Documentation des sources de données (d'où viennent les données brutes)
sources:
  - name: pokeapi
    description: "Données extraites de l'API PokeAPI"
    tables:
      - name: pokemon
        description: "Données de base des Pokémon"
        columns:
          - name: id
            description: "ID du Pokémon"
          - name: name
            description: "Nom du Pokémon"
          - name: height
            description: "Taille en décimètres"
          - name: weight
            description: "Poids en hectogrammes"
          - name: types
            description: "Types du Pokémon (format JSON)"
          - name: stats
            description: "Statistiques du Pokémon (format JSON)"
          - name: abilities
            description: "Capacités du Pokémon (format JSON)"
          - name: sprites
            description: "URLs des images du Pokémon (format JSON)"
          - name: cries
            description: "URLs des cris du Pokémon (format JSON)"
          - name: moves
            description: "Attaques du Pokémon (format JSON)"

      - name: pokemon_species
        description: "Données d'espèces Pokémon" 
        columns:
          - name: id
            description: "ID de l'espèce"
          - name: name
            description: "Nom de l'espèce"
          - name: evolution_chain
            description: "Lien vers la chaîne d'évolution"
          - name: generation
            description: "Génération du Pokémon"
          - name: capture_rate
            description: "Taux de capture"
          - name: base_happiness
            description: "Bonheur de base"
          - name: is_legendary
            description: "Si l'espèce est légendaire"
          - name: is_mythical
            description: "Si l'espèce est mythique"

      - name: evolution_chain
        description: "Chaînes d'évolution des Pokémon"
        columns:
          - name: id
            description: "ID de la chaîne d'évolution"
          - name: chain
            description: "Structure de la chaîne d'évolution (format JSON)"

      - name: move
        description: "Données d'attaques Pokémon"
        columns:
          - name: id
            description: "ID de l'attaque"
          - name: name
            description: "Nom de l'attaque"
          - name: type
            description: "Type de l'attaque (format JSON)"
          - name: power
            description: "Puissance de l'attaque"
          - name: pp
            description: "Points de pouvoir (PP)"
          - name: accuracy
            description: "Précision de l'attaque"
          - name: effect_entries
            description: "Description des effets (format JSON)"

      - name: ability
        description: "Données de capacités Pokémon"
        columns:
          - name: id
            description: "ID de la capacité"
          - name: name
            description: "Nom de la capacité"
          - name: effect_entries
            description: "Description des effets (format JSON)"

      - name: type
        description: "Types de Pokémon"
        columns:
          - name: id
            description: "ID du type"
          - name: name
            description: "Nom du type"
          - name: damage_relations
            description: "Relations de dégâts avec autres types (format JSON)" 