CREATE TABLE IF NOT EXISTS pokedex_numbers(
    pokemon_id INTEGER PRIMARY KEY,
    national INTEGER NULL,
    kanto INTEGER NULL,
    original_johto INTEGER NULL,
    updated_johto INTEGER NULL,
    hoenn INTEGER NULL,
    original_sinnoh INTEGER NULL,
    extended_sinnoh INTEGER NULL,
    unova_bw INTEGER NULL,
    unova_b2w2 INTEGER NULL,
    kalos_central INTEGER NULL,
    kalos_coastal INTEGER NULL,
    kalos_mountain INTEGER NULL,
    alola INTEGER NULL,
    melemele INTEGER NULL,
    akala INTEGER NULL,
    ulaula INTEGER NULL,
    poni INTEGER NULL,
    galar INTEGER NULL,
    isle_of_armor INTEGER NULL,
    crown_tundra INTEGER NULL,
    hisui INTEGER NULL,
    paldea INTEGER NULL
);