CREATE TABLE IF NOT EXISTS pokemon_details(
    id INTEGER PRIMARY KEY,
    species_id INTEGER NOT NULL,
    name_en VARCHAR(100) NOT NULL UNIQUE,
    name_fr VARCHAR(100) NULL UNIQUE,
    type_1_id INTEGER NOT NULL,
    type_1 VARCHAR(20) NOT NULL,
    type_2_id INTEGER NULL,
    type_2 VARCHAR(20) NULL,
    height_m INTEGER NOT NULL,
    weight_kg INTEGER NOT NULL,
    base_experience INTEGER NULL,
    order INTEGER NULL,
    is_default BOOLEAN NOT NULL,
    is_legendary BOOLEAN NOT NULL DEFAULT FALSE,
    is_mythical BOOLEAN NOT NULL DEFAULT FALSE,
    is_baby BOOLEAN NOT NULL DEFAULT FALSE,
    gender_rate INTEGER NULL,
    capture_rate INTEGER NULL,
    base_happiness INTEGER NULL,
    hatch_counter INTEGER NULL,
    has_gender_differences BOOLEAN NULL DEFAULT FALSE,
    forms_switchable BOOLEAN NULL DEFAULT FALSE,
    egg_group_1 VARCHAR(20) NULL,
    egg_group_2 VARCHAR(20) NULL,
    color VARCHAR(20) NULL,
    shape VARCHAR(20) NULL,
    evolves_from_species_id INTEGER NULL,
    evolution_chain_id INTEGER NULL,
    habitat VARCHAR(20) NULL,
    generation VARCHAR(20) NULL,
    growth_rate VARCHAR(20) NULL
);