name: CI/CD Pipeline

on:
  push:
    branches: [ main, feat/ml_api ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install --with-deps chromium
        
    - name: Run tests
      run: |
        # Démarrer l'application Streamlit en arrière-plan pour les tests locaux
        # (désactivé car nous testons sur l'app déployée)
        # nohup streamlit run app/streamlit_app.py &
        # sleep 10  # Attendre que l'app démarre
        
        # Exécuter les tests
        python -m pytest tests/test_app.py -v
        
  deploy:
    needs: test  # Ce job s'exécute uniquement si le job 'test' réussit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/ml_api')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Le déploiement sur Streamlit Cloud est automatique via GitHub."
        echo "Streamlit Cloud détecte les changements dans le dépôt et déploie automatiquement."
        
    # Si vous avez besoin de déployer sur d'autres plateformes, ajoutez les étapes ici 